description: "Muhlenberg College EMS is the student-run emergency medical services organization for Muhlenberg College in Allentown, PA"
keywords:
  - mcems
  - muhlenberg college ems
  - ems
  - emt
  - allentown
  - lehigh county ems
sass:
  style: compressed
nav:
  - url: /learn-cpr/index.html
    href: /learn-cpr/
    text: Learn CPR
  - url: /join-mcems/index.html
    href: /join-mcems/
    text: Join MCEMS
  - url: /apparatus/index.html
    href: /apparatus/
    text: Apparatus
  - url: /faq/index.html
    href: /faq/
    text: FAQ
  - url: /officers/index.html
    href: /officers/
    text: Officers
  - url: /contact/index.html
    href: /contact/
    text: Contact
membership:
  emt: ???
  training_corps: 12iuhiuh
