description: "Muhlenberg College EMS is the student-run emergency medical services organization for Muhlenberg College in Allentown, PA"
keywords:
  - mcems
  - muhlenberg college ems
  - ems
  - emt
  - allentown
  - lehigh county ems
sass:
  style: compressed
timezone: Etc/GMT
